project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "Sheep observer"
  site-url: "https://sheep.observer/"
  description: "Szymon Bęczkowski's blog"
  navbar:
    right:
      - icon: rss
        href: all.xml
    left:
      - text: "programming"
        icon: terminal
        file: programming.qmd
      - text: "electronics"
        icon: lightning
        file: electronics.qmd
      - text: "openstreetmap"
        icon: map
        file: openstreetmap.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    toc: false
    minimal: true
    html-math-method: mathjax
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Merriweather" type="text/css"/>
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Raleway" type="text/css"/>
    mainfont: Merriweather
    fontsize: 1rem
    linestretch: 1.75
