project:
  type: website

website:
  title: "Sheep observer"
  site-url: "https://sheep.observer/"
  navbar:
    left:
      - text: "programming"
        icon: terminal
        file: programming.qmd
      - text: "electronics"
        icon: lightning
        file: electronics.qmd
      - text: "openstreetmap"
        icon: map
        file: openstreetmap.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    minimal: true
    html-math-method: mathjax
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Merriweather" type="text/css"/>
    mainfont: Merriweather
    fontsize: 1rem
    linestretch: 1.75
